### PR TITLE
Add package discovery

### PR DESCRIPTION
**Pull request by danmichaelo**
Adding support for Laravel package discovery, a feature added in Laravel 5.5

### CODE REVIEW

**Review by Nyholm — APPROVED** [review]
Excellent. Thank you. I think this all looks good.

**Review by welcoMattic — APPROVED** [review]

**Comment by jitendra-1217** [comment]
When will this be ~merged~ released?

**Comment by Nyholm** [comment]
Oops. This has been hanging for 2 years. 
Sorry about that. :/

**Comment by Nyholm** [comment]
@jitendra-1217 Can you test dev-master. When you report that everything is working, then I'll make a release.

**Pull request merged**
