### PR TITLE
add client-common instead of client-implementations

### PR DESCRIPTION
**Pull request by welcoMattic**

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you for this PR. Why wouldn't you need the client implementation?

**Comment by welcoMattic** [comment]
It's not available anymore. Not?

**Comment by Nyholm** [comment]
It is a virtual package that make sure you have at least one httplug client implemented. See https://packagist.org/providers/php-http/client-implementation

What classes do we use from client-common? Are we using any plugins?

**Comment by welcoMattic** [comment]
Oh ok, my bad. I didn't know that you use virtual package. 
Thanks for your explanation

**Comment by Nyholm** [comment]
No worries =)

**Pull request closed without merging**
